version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: tasktracker-bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TIMEZONE=Europe/Moscow
      - DAILY_REPORT_TIME=09:00
      - DATABASE_PATH=/app/data/bot.db
    volumes:
      - ./data:/app/data
    env_file:
      - .env



